[package]
name = "DepthLudum"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.15.3", features = ["shader_format_glsl"] }
bevy_asset_loader = "0.22.0"
bevy_enhanced_input = "0.8.0"
bevy_tweening = "0.12.0"
bevy_rapier2d = "0.29.0"
noisy_bevy = "0.8.0"
